---
name: Package

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - develop

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv

      - name: Build package
        run: |
          $env:PIPENV_VENV_IN_PROJECT = 1
          pipenv install --dev
          pipenv run python -m pip list
          pipenv run pyinstaller --onedir --noconsole --clean --noconfirm `
            --add-data "ssm_manager\static:ssm_manager\static" `
            --add-data "ssm_manager\templates:ssm_manager\templates" `
            --icon="ssm_manager\static\favicon.ico" `
            --name="ssm_manager" `
            main.py
          mkdir release
          Compress-Archive -Path "dist\ssm_manager\*" -DestinationPath "release\ssm_manager.zip" -Force
          cd dist\ssm_manager
          7z a -sfx "${{ github.workspace }}\release\ssm_manager.exe" *
          cd -

      - name: Upload ssm_manager.zip
        uses: actions/upload-artifact@v4
        with:
          name: ssm_manager_zip
          path: release/ssm_manager.zip
          if-no-files-found: error
          overwrite: true

      - name: Upload ssm_manager.exe
        uses: actions/upload-artifact@v4
        with:
          name: ssm_manager_exe
          path: release/ssm_manager.exe
          if-no-files-found: error
          overwrite: true

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download ssm_manager.zip
        uses: actions/download-artifact@v4
        with:
          name: ssm_manager_zip

      - name: Download ssm_manager.exe
        uses: actions/download-artifact@v4
        with:
          name: ssm_manager_exe

      - name: Create develop release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/heads/develop')
        with:
          tag_name: dev
          files: |
            ssm_manager.zip
            ssm_manager.exe
          make_latest: false
          body: |
            **** Development Release ****

            This build is for development purposes only.

      - name: Create tagged release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            ssm_manager.zip
            ssm_manager.exe
          make_latest: true
          body: |
            Release ${{ github.ref_name }}
