---
name: Package

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv

      - name: Build package
        run: |
          cd ssm-manager
          $env:PIPENV_VENV_IN_PROJECT = 1
          pipenv install --dev
          pipenv run pyinstaller --onedir --noconsole --clean --noconfirm --add-data "static:static" --add-data "templates:templates" --icon="static\favicon.ico" --name="ssm-manager" app.py
          mkdir release
          Compress-Archive -Path "dist\*" -DestinationPath "release\ssm-manager.zip" -Force

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: ssm-manager
          path: ssm-manager/release/ssm-manager.zip
          if-no-files-found: error
          overwrite: true

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download package
        id: package
        uses: actions/download-artifact@v4
        with:
          name: ssm-manager

      - name: Create develop release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/heads/develop')
        with:
          tag_name: ${{ github.ref_name }}
          files: ssm-manager.zip
          make_latest: false
          body: |
            **** Development Release ****

            This build is for development purposes only.

      - name: Create tagged release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          tag_name: ${{ github.ref_name }}
          files: ssm-manager.zip
          make_latest: true
          body: |
            Release ${{ github.ref_name }}
