---
name: Package

on:
  push:
    # tags:
    #   - 'v*.*.*'
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install --dev

      - name: Build package
        run: |
          cd ssm-manager
          pipenv run pyinstaller --onedir --noconsole --clean --noconfirm --add-data "static:static" --add-data "templates:templates" --icon="static/favicon.ico" --name="ssm-manager" app.py

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: ssm-manager
          path: dist/ssm-manager/*
          if-no-files-found: error
          overwrite: true
